# Generated by Django 6.0.1 on 2026-02-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0006_rename_agecategories_agecategory_and_more'),
        ('competitions', '0003_rename_date_competition_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('result_value', models.DecimalField(decimal_places=2, help_text='Time (seconds) or distance (meters)', max_digits=7)),
                ('result_date', models.DateField()),
                ('age_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='athletes.agecategory')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='athletes.athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='athletes.discipline')),
            ],
        ),
    ]
