# Generated by Django 6.0.1 on 2026-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('U14', 'Under 14'), ('U16', 'Under 16'), ('U18', 'Under 18'), ('U20', 'Under 20'), ('U23', 'Under 23'), ('SEN', 'Senior / Open'), ('V35', 'Veterans 35–39'), ('V40', 'Veterans 40–44'), ('V45', 'Veterans 45–49'), ('V50', 'Veterans 50–54'), ('V55', 'Veterans 55–59'), ('V60', 'Veterans 60+')], max_length=4, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
