# Generated by Django 6.0.1 on 2026-01-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_agecategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='athletes',
            name='disciplines',
            field=models.ManyToManyField(related_name='athletes', to='athletes.discipline'),
        ),
    ]
