# Generated by Django 6.0.1 on 2026-01-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_alter_agecategories_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discipline',
            new_name='Disciplines',
        ),
    ]
