# Generated by Django 6.0.1 on 2026-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_rename_discipline_disciplines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeCategories',
            new_name='AgeCategory',
        ),
        migrations.RenameModel(
            old_name='Disciplines',
            new_name='Discipline',
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplines', models.ManyToManyField(related_name='athlete', to='athletes.discipline')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.DeleteModel(
            name='Athletes',
        ),
    ]
