# Generated by Django 6.0.1 on 2026-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_rename_agecategories_agecategory_and_more'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='age_groups',
            field=models.ManyToManyField(related_name='competitions', to='athletes.agecategory'),
        ),
    ]
