# Generated by Django 6.0.1 on 2026-01-18 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_age_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
    ]
